# Generated by Django 3.1.2 on 2020-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poll_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_que', models.TextField()),
                ('poll_option1', models.CharField(max_length=30)),
                ('poll_option2', models.CharField(max_length=30)),
                ('poll_option3', models.CharField(max_length=30)),
                ('poll_option4', models.CharField(max_length=30)),
                ('poll_option1_count', models.IntegerField(default=0)),
                ('poll_option2_count', models.IntegerField(default=0)),
                ('poll_option3_count', models.IntegerField(default=0)),
                ('poll_option4_count', models.IntegerField(default=0)),
            ],
        ),
    ]
